Document: unwrap360
Title: Debian unwrap360 Manual
Author: <insert document author here>
Abstract: This manual describes what unwrap360 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/unwrap360/unwrap360.sgml.gz

Format: postscript
Files: /usr/share/doc/unwrap360/unwrap360.ps.gz

Format: text
Files: /usr/share/doc/unwrap360/unwrap360.text.gz

Format: HTML
Index: /usr/share/doc/unwrap360/html/index.html
Files: /usr/share/doc/unwrap360/html/*.html


